In [7]:
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [8]:

draw_korea_raw = pd.read_csv('data/05. draw_korea_raw.csv')

draw_korea_raw

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,철원,화천,양구,고성(강원),NaN,NaN,NaN
1,NaN,NaN,NaN,양주,동두천,연천,포천,의정부,인제,춘천,속초,NaN,NaN,NaN
2,NaN,NaN,NaN,고양 덕양,고양 일산동,서울 도봉,서울 노원,남양주,홍천,횡성,양양,NaN,NaN,NaN
3,NaN,NaN,파주,고양 일산서,김포,서울 강북,서울 성북,가평,구리,하남,정선,강릉,NaN,NaN
4,NaN,NaN,부천 소사,안양 만안,광명,서울 서대문,서울 종로,서울 동대문,서울 중랑,양평,태백,동해,NaN,NaN
5,NaN,인천 강화,부천 원미,안양 동안,서울 은평,서울 마포,서울 중구,서울 성동,서울 강동,여주,원주,삼척,NaN,NaN
6,NaN,인천 서구,부천 오정,시흥,서울 강서,서울 동작,서울 용산,서울 광진,서울 송파,이천,평창,울진,NaN,NaN
7,NaN,인천 동구,인천 계양,안산 상록,서울 양천,서울 관악,서울 서초,성남 중원,과천,광주,영월,영덕,NaN,NaN
8,NaN,NaN,인천 부평,안산 단원,서울 영등포,서울 금천,서울 강남,성남 분당,성남 수정,용인 수지,문경,봉화,NaN,울릉
9,NaN,인천 중구,인천 남구,화성,서울 구로,군포,의왕,수원 영통,용인 기흥,용인 처인,안동,영양,NaN,NaN
10,인천 옹진,인천 연수,인천 남동,오산,안성,수원 권선,수원 장안,제천,예천,영주,구미,청송,포항 북구,NaN
11,태안,아산,천안 동남,천안 서북,평택,음성,수원 팔달,단양,상주,김천,군위,의성,포항 남구,NaN
12,NaN,당진,홍성,예산,공주,진천,충주,청주 흥덕,괴산,칠곡,영천,경산,경주,NaN
13,NaN,서산,보령,청양,세종,대전 대덕,증평,청주 청원,보은,고령,청도,성주,울산 북구,NaN
14,NaN,NaN,부여,논산,계룡,대전 동구,청주 상당,청주 서원,대구 북구,대구 중구,대구 수성,울산 울주,울산 동구,NaN
15,NaN,NaN,서천,금산,대전 유성,대전 중구,옥천,영동,대구 서구,대구 남구,대구 동구,울산 중구,울산 남구,NaN
16,NaN,NaN,군산,익산,대전 서구,무주,거창,합천,대구 달서,대구 달성,부산 금정,부산 동래,부산 기장,NaN
17,NaN,NaN,부안,김제,완주,장수,함양,창녕,밀양,부산 북구,부산 부산진,부산 연제,부산 해운대,NaN
18,NaN,고창,정읍,전주 덕진,진안,남원,진주,의령,부산 강서,부산 사상,부산 동구,부산 중구,NaN,NaN
19,NaN,영광,장성,전주 완산,임실,산청,함안,양산,창원 합포,부산 서구,부산 사하,부산 남구,NaN,NaN
20,NaN,함평,담양,순창,구례,하동,창원 의창,창원 성산,창원 진해,김해,부산 영도,부산 수영,NaN,NaN
21,신안,무안,광주 광산,곡성,화순,광양,사천,창원 회원,통영,NaN,NaN,NaN,NaN,NaN
22,목포,나주,광주 서구,광주 북구,순천,고흥,남해,고성(경남),거제,NaN,NaN,NaN,NaN,NaN
23,해남,영암,광주 남구,광주 동구,여수,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,진도,강진,장흥,보성,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,완도,NaN,NaN,제주,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,서귀포,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
draw_korea_raw_stacked = pd.DataFrame(draw_korea_raw.stack())
draw_korea_raw_stacked.reset_index(inplace=True)
draw_korea_raw_stacked.rename(columns={'level_0':'y', 'level_1':'x', 0:'ID'}, 
                              inplace=True)

draw_korea_raw_stacked

      y   x      ID
0     0   7      철원
1     0   8      화천
2     0   9      양구
3     0  10  고성(강원)
4     1   3      양주
..   ..  ..     ...
247  24   2      장흥
248  24   3      보성
249  25   2      완도
250  25   5      제주
251  26   5     서귀포

[252 rows x 3 columns]

In [10]:
draw_korea = draw_korea_raw_stacked

In [11]:
BORDER_LINES = [
    [(5,1), (5,2), (7,2), (7,3), (11,3), (11,0)], # 인천
    [(5,4), (5,5), (2,5), (2,7), (4,7), (4,9), (7,9), 
     (7,7), (9,7), (9,5), (10,5), (10,4), (5,4)], # 서울
    [(1,7), (1,8), (3,8), (3,10), (10,10), (10,7), 
     (12,7), (12,6), (11,6), (11,5), (12, 5), (12,4), 
     (11,4), (11,3)], # 경기도
    [(8,10), (8,11), (6,11), (6,12)], # 강원도
    [(12,5), (13,5), (13,4), (14,4), (14,5), (15,5), 
     (15,4), (16,4), (16,2)], # 충청북도
    [(16,4), (17,4), (17,5), (16,5), (16,6), (19,6), 
     (19,5), (20,5), (20,4), (21,4), (21,3), (19,3), (19,1)], # 전라북도
    [(13,5), (13,6), (16,6)], # 대전시
    [(13,5), (14,5)], #세종시
    [(21,2), (21,3), (22,3), (22,4), (24,4), (24,2), (21,2)], #광주
    [(20,5), (21,5), (21,6), (23,6)], #전라남도
    [(10,8), (12,8), (12,9), (14,9), (14,8), (16,8), (16,6)], #충청북도
    [(14,9), (14,11), (14,12), (13,12), (13,13)], #경상북도
    [(15,8), (17,8), (17,10), (16,10), (16,11), (14,11)], #대구
    [(17,9), (18,9), (18,8), (19,8), (19,9), (20,9), (20,10), (21,10)], #부산
    [(16,11), (16,13)], #울산
#     [(9,14), (9,15)], 
    [(27,5), (27,6), (25,6)],
]

In [29]:
draw_korea.iterrows()

In [39]:
plt.figure(figsize=(8, 11))

# 지역 이름 표시
for idx, row in draw_korea.iterrows():
    
    # 광역시는 구 이름이 겹치는 경우가 많아서 시단위 이름도 같이 표시한다. 
    # (중구, 서구)
    if len(row['ID'].split())==2:
        dispname = '{}\n{}'.format(row['ID'].split()[0], row['ID'].split()[1])
    elif row['ID'][:2]=='고성':
        dispname = '고성'
    else:
        dispname = row['ID']
        
    #row['x'] = int(row['x'])

    # 서대문구, 서귀포시 같이 이름이 3자 이상인 경우에 작은 글자로 표시한다.
    if len(dispname.splitlines()[-1]) >= 3:
        fontsize, linespacing = 9.5, 1.5
    else:
        fontsize, linespacing = 11, 1.2
    print(dispname)
    print(type(dispname))
    print(row['x'])
    print(type(row['x']))
    print(row['y'])
    print(type(row['y']))

철원
<class 'str'>
7
<class 'str'>
0
<class 'int'>
화천
<class 'str'>
8
<class 'str'>
0
<class 'int'>
양구
<class 'str'>
9
<class 'str'>
0
<class 'int'>
고성
<class 'str'>
10
<class 'str'>
0
<class 'int'>
양주
<class 'str'>
3
<class 'str'>
1
<class 'int'>
동두천
<class 'str'>
4
<class 'str'>
1
<class 'int'>
연천
<class 'str'>
5
<class 'str'>
1
<class 'int'>
포천
<class 'str'>
6
<class 'str'>
1
<class 'int'>
의정부
<class 'str'>
7
<class 'str'>
1
<class 'int'>
인제
<class 'str'>
8
<class 'str'>
1
<class 'int'>
춘천
<class 'str'>
9
<class 'str'>
1
<class 'int'>
속초
<class 'str'>
10
<class 'str'>
1
<class 'int'>
고양
덕양
<class 'str'>
3
<class 'str'>
2
<class 'int'>
고양
일산동
<class 'str'>
4
<class 'str'>
2
<class 'int'>
서울
도봉
<class 'str'>
5
<class 'str'>
2
<class 'int'>
서울
노원
<class 'str'>
6
<class 'str'>
2
<class 'int'>
남양주
<class 'str'>
7
<class 'str'>
2
<class 'int'>
홍천
<class 'str'>
8
<class 'str'>
2
<class 'int'>
횡성
<class 'str'>
9
<class 'str'>
2
<class 'int'>
양양
<class 'str'>
10
<class 'str'>
2
<class 'int'>
파주
<class 'str'>
2
<class 'str'>
3
<class 'int'>
고양
일산서
<class 'str'>
3
<class 'str'>
3
<class 'int'>
김포
<class 'str'>
4
<class 'str'>
3
<class 'int'>
서울
강북
<class 'str'>
5
<class 'str'>
3
<class 'int'>
서울
성북
<class 'str'>
6
<class 'str'>
3
<class 'int'>
가평
<class 'str'>
7
<class 'str'>
3
<class 'int'>
구리
<class 'str'>
8
<class 'str'>
3
<class 'int'>
하남
<class 'str'>
9
<class 'str'>
3
<class 'int'>
정선
<class 'str'>
10
<class 'str'>
3
<class 'int'>
강릉
<class 'str'>
11
<class 'str'>
3
<class 'int'>
부천
소사
<class 'str'>
2
<class 'str'>
4
<class 'int'>
안양
만안
<class 'str'>
3
<class 'str'>
4
<class 'int'>
광명
<class 'str'>
4
<class 'str'>
4
<class 'int'>
서울
서대문
<class 'str'>
5
<class 'str'>
4
<class 'int'>
서울
종로
<class 'str'>
6
<class 'str'>
4
<class 'int'>
서울
동대문
<class 'str'>
7
<class 'str'>
4
<class 'int'>
서울
중랑
<class 'str'>
8
<class 'str'>
4
<class 'int'>
양평
<class 'str'>
9
<class 'str'>
4
<class 'int'>
태백
<class 'str'>
10
<class 'str'>
4
<class 'int'>
동해
<class 'str'>
11
<class 'str'>
4
<class 'int'>
인천
강화
<class 'str'>
1
<class 'str'>
5
<class 'int'>
부천
원미
<class 'str'>
2
<class 'str'>
5
<class 'int'>
안양
동안
<class 'str'>
3
<class 'str'>
5
<class 'int'>
서울
은평
<class 'str'>
4
<class 'str'>
5
<class 'int'>
서울
마포
<class 'str'>
5
<class 'str'>
5
<class 'int'>
서울
중구
<class 'str'>
6
<class 'str'>
5
<class 'int'>
서울
성동
<class 'str'>
7
<class 'str'>
5
<class 'int'>
서울
강동
<class 'str'>
8
<class 'str'>
5
<class 'int'>
여주
<class 'str'>
9
<class 'str'>
5
<class 'int'>
원주
<class 'str'>
10
<class 'str'>
5
<class 'int'>
삼척
<class 'str'>
11
<class 'str'>
5
<class 'int'>
인천
서구
<class 'str'>
1
<class 'str'>
6
<class 'int'>
부천
오정
<class 'str'>
2
<class 'str'>
6
<class 'int'>
시흥
<class 'str'>
3
<class 'str'>
6
<class 'int'>
서울
강서
<class 'str'>
4
<class 'str'>
6
<class 'int'>
서울
동작
<class 'str'>
5
<class 'str'>
6
<class 'int'>
서울
용산
<class 'str'>
6
<class 'str'>
6
<class 'int'>
서울
광진
<class 'str'>
7
<class 'str'>
6
<class 'int'>
서울
송파
<class 'str'>
8
<class 'str'>
6
<class 'int'>
이천
<class 'str'>
9
<class 'str'>
6
<class 'int'>
평창
<class 'str'>
10
<class 'str'>
6
<class 'int'>
울진
<class 'str'>
11
<class 'str'>
6
<class 'int'>
인천
동구
<class 'str'>
1
<class 'str'>
7
<class 'int'>
인천
계양
<class 'str'>
2
<class 'str'>
7
<class 'int'>
안산
상록
<class 'str'>
3
<class 'str'>
7
<class 'int'>
서울
양천
<class 'str'>
4
<class 'str'>
7
<class 'int'>
서울
관악
<class 'str'>
5
<class 'str'>
7
<class 'int'>
서울
서초
<class 'str'>
6
<class 'str'>
7
<class 'int'>
성남
중원
<class 'str'>
7
<class 'str'>
7
<class 'int'>
과천
<class 'str'>
8
<class 'str'>
7
<class 'int'>
광주
<class 'str'>
9
<class 'str'>
7
<class 'int'>
영월
<class 'str'>
10
<class 'str'>
7
<class 'int'>
영덕
<class 'str'>
11
<class 'str'>
7
<class 'int'>
인천
부평
<class 'str'>
2
<class 'str'>
8
<class 'int'>
안산
단원
<class 'str'>
3
<class 'str'>
8
<class 'int'>
서울
영등포
<class 'str'>
4
<class 'str'>
8
<class 'int'>
서울
금천
<class 'str'>
5
<class 'str'>
8
<class 'int'>
서울
강남
<class 'str'>
6
<class 'str'>
8
<class 'int'>
성남
분당
<class 'str'>
7
<class 'str'>
8
<class 'int'>
성남
수정
<class 'str'>
8
<class 'str'>
8
<class 'int'>
용인
수지
<class 'str'>
9
<class 'str'>
8
<class 'int'>
문경
<class 'str'>
10
<class 'str'>
8
<class 'int'>
봉화
<class 'str'>
11
<class 'str'>
8
<class 'int'>
울릉
<class 'str'>
13
<class 'str'>
8
<class 'int'>
인천
중구
<class 'str'>
1
<class 'str'>
9
<class 'int'>
인천
남구
<class 'str'>
2
<class 'str'>
9
<class 'int'>
화성
<class 'str'>
3
<class 'str'>
9
<class 'int'>
서울
구로
<class 'str'>
4
<class 'str'>
9
<class 'int'>
군포
<class 'str'>
5
<class 'str'>
9
<class 'int'>
의왕
<class 'str'>
6
<class 'str'>
9
<class 'int'>
수원
영통
<class 'str'>
7
<class 'str'>
9
<class 'int'>
용인
기흥
<class 'str'>
8
<class 'str'>
9
<class 'int'>
용인
처인
<class 'str'>
9
<class 'str'>
9
<class 'int'>
안동
<class 'str'>
10
<class 'str'>
9
<class 'int'>
영양
<class 'str'>
11
<class 'str'>
9
<class 'int'>
인천
옹진
<class 'str'>
0
<class 'str'>
10
<class 'int'>
인천
연수
<class 'str'>
1
<class 'str'>
10
<class 'int'>
인천
남동
<class 'str'>
2
<class 'str'>
10
<class 'int'>
오산
<class 'str'>
3
<class 'str'>
10
<class 'int'>
안성
<class 'str'>
4
<class 'str'>
10
<class 'int'>
수원
권선
<class 'str'>
5
<class 'str'>
10
<class 'int'>
수원
장안
<class 'str'>
6
<class 'str'>
10
<class 'int'>
제천
<class 'str'>
7
<class 'str'>
10
<class 'int'>
예천
<class 'str'>
8
<class 'str'>
10
<class 'int'>
영주
<class 'str'>
9
<class 'str'>
10
<class 'int'>
구미
<class 'str'>
10
<class 'str'>
10
<class 'int'>
청송
<class 'str'>
11
<class 'str'>
10
<class 'int'>
포항
북구
<class 'str'>
12
<class 'str'>
10
<class 'int'>
태안
<class 'str'>
0
<class 'str'>
11
<class 'int'>
아산
<class 'str'>
1
<class 'str'>
11
<class 'int'>
천안
동남
<class 'str'>
2
<class 'str'>
11
<class 'int'>
천안
서북
<class 'str'>
3
<class 'str'>
11
<class 'int'>
평택
<class 'str'>
4
<class 'str'>
11
<class 'int'>
음성
<class 'str'>
5
<class 'str'>
11
<class 'int'>
수원
팔달
<class 'str'>
6
<class 'str'>
11
<class 'int'>
단양
<class 'str'>
7
<class 'str'>
11
<class 'int'>
상주
<class 'str'>
8
<class 'str'>
11
<class 'int'>
김천
<class 'str'>
9
<class 'str'>
11
<class 'int'>
군위
<class 'str'>
10
<class 'str'>
11
<class 'int'>
의성
<class 'str'>
11
<class 'str'>
11
<class 'int'>
포항
남구
<class 'str'>
12
<class 'str'>
11
<class 'int'>
당진
<class 'str'>
1
<class 'str'>
12
<class 'int'>
홍성
<class 'str'>
2
<class 'str'>
12
<class 'int'>
예산
<class 'str'>
3
<class 'str'>
12
<class 'int'>
공주
<class 'str'>
4
<class 'str'>
12
<class 'int'>
진천
<class 'str'>
5
<class 'str'>
12
<class 'int'>
충주
<class 'str'>
6
<class 'str'>
12
<class 'int'>
청주
흥덕
<class 'str'>
7
<class 'str'>
12
<class 'int'>
괴산
<class 'str'>
8
<class 'str'>
12
<class 'int'>
칠곡
<class 'str'>
9
<class 'str'>
12
<class 'int'>
영천
<class 'str'>
10
<class 'str'>
12
<class 'int'>
경산
<class 'str'>
11
<class 'str'>
12
<class 'int'>
경주
<class 'str'>
12
<class 'str'>
12
<class 'int'>
서산
<class 'str'>
1
<class 'str'>
13
<class 'int'>
보령
<class 'str'>
2
<class 'str'>
13
<class 'int'>
청양
<class 'str'>
3
<class 'str'>
13
<class 'int'>
세종
<class 'str'>
4
<class 'str'>
13
<class 'int'>
대전
대덕
<class 'str'>
5
<class 'str'>
13
<class 'int'>
증평
<class 'str'>
6
<class 'str'>
13
<class 'int'>
청주
청원
<class 'str'>
7
<class 'str'>
13
<class 'int'>
보은
<class 'str'>
8
<class 'str'>
13
<class 'int'>
고령
<class 'str'>
9
<class 'str'>
13
<class 'int'>
청도
<class 'str'>
10
<class 'str'>
13
<class 'int'>
성주
<class 'str'>
11
<class 'str'>
13
<class 'int'>
울산
북구
<class 'str'>
12
<class 'str'>
13
<class 'int'>
부여
<class 'str'>
2
<class 'str'>
14
<class 'int'>
논산
<class 'str'>
3
<class 'str'>
14
<class 'int'>
계룡
<class 'str'>
4
<class 'str'>
14
<class 'int'>
대전
동구
<class 'str'>
5
<class 'str'>
14
<class 'int'>
청주
상당
<class 'str'>
6
<class 'str'>
14
<class 'int'>
청주
서원
<class 'str'>
7
<class 'str'>
14
<class 'int'>
대구
북구
<class 'str'>
8
<class 'str'>
14
<class 'int'>
대구
중구
<class 'str'>
9
<class 'str'>
14
<class 'int'>
대구
수성
<class 'str'>
10
<class 'str'>
14
<class 'int'>
울산
울주
<class 'str'>
11
<class 'str'>
14
<class 'int'>
울산
동구
<class 'str'>
12
<class 'str'>
14
<class 'int'>
서천
<class 'str'>
2
<class 'str'>
15
<class 'int'>
금산
<class 'str'>
3
<class 'str'>
15
<class 'int'>
대전
유성
<class 'str'>
4
<class 'str'>
15
<class 'int'>
대전
중구
<class 'str'>
5
<class 'str'>
15
<class 'int'>
옥천
<class 'str'>
6
<class 'str'>
15
<class 'int'>
영동
<class 'str'>
7
<class 'str'>
15
<class 'int'>
대구
서구
<class 'str'>
8
<class 'str'>
15
<class 'int'>
대구
남구
<class 'str'>
9
<class 'str'>
15
<class 'int'>
대구
동구
<class 'str'>
10
<class 'str'>
15
<class 'int'>
울산
중구
<class 'str'>
11
<class 'str'>
15
<class 'int'>
울산
남구
<class 'str'>
12
<class 'str'>
15
<class 'int'>
군산
<class 'str'>
2
<class 'str'>
16
<class 'int'>
익산
<class 'str'>
3
<class 'str'>
16
<class 'int'>
대전
서구
<class 'str'>
4
<class 'str'>
16
<class 'int'>
무주
<class 'str'>
5
<class 'str'>
16
<class 'int'>
거창
<class 'str'>
6
<class 'str'>
16
<class 'int'>
합천
<class 'str'>
7
<class 'str'>
16
<class 'int'>
대구
달서
<class 'str'>
8
<class 'str'>
16
<class 'int'>
대구
달성
<class 'str'>
9
<class 'str'>
16
<class 'int'>
부산
금정
<class 'str'>
10
<class 'str'>
16
<class 'int'>
부산
동래
<class 'str'>
11
<class 'str'>
16
<class 'int'>
부산
기장
<class 'str'>
12
<class 'str'>
16
<class 'int'>
부안
<class 'str'>
2
<class 'str'>
17
<class 'int'>
김제
<class 'str'>
3
<class 'str'>
17
<class 'int'>
완주
<class 'str'>
4
<class 'str'>
17
<class 'int'>
장수
<class 'str'>
5
<class 'str'>
17
<class 'int'>
함양
<class 'str'>
6
<class 'str'>
17
<class 'int'>
창녕
<class 'str'>
7
<class 'str'>
17
<class 'int'>
밀양
<class 'str'>
8
<class 'str'>
17
<class 'int'>
부산
북구
<class 'str'>
9
<class 'str'>
17
<class 'int'>
부산
부산진
<class 'str'>
10
<class 'str'>
17
<class 'int'>
부산
연제
<class 'str'>
11
<class 'str'>
17
<class 'int'>
부산
해운대
<class 'str'>
12
<class 'str'>
17
<class 'int'>
고창
<class 'str'>
1
<class 'str'>
18
<class 'int'>
정읍
<class 'str'>
2
<class 'str'>
18
<class 'int'>
전주
덕진
<class 'str'>
3
<class 'str'>
18
<class 'int'>
진안
<class 'str'>
4
<class 'str'>
18
<class 'int'>
남원
<class 'str'>
5
<class 'str'>
18
<class 'int'>
진주
<class 'str'>
6
<class 'str'>
18
<class 'int'>
의령
<class 'str'>
7
<class 'str'>
18
<class 'int'>
부산
강서
<class 'str'>
8
<class 'str'>
18
<class 'int'>
부산
사상
<class 'str'>
9
<class 'str'>
18
<class 'int'>
부산
동구
<class 'str'>
10
<class 'str'>
18
<class 'int'>
부산
중구
<class 'str'>
11
<class 'str'>
18
<class 'int'>
영광
<class 'str'>
1
<class 'str'>
19
<class 'int'>
장성
<class 'str'>
2
<class 'str'>
19
<class 'int'>
전주
완산
<class 'str'>
3
<class 'str'>
19
<class 'int'>
임실
<class 'str'>
4
<class 'str'>
19
<class 'int'>
산청
<class 'str'>
5
<class 'str'>
19
<class 'int'>
함안
<class 'str'>
6
<class 'str'>
19
<class 'int'>
양산
<class 'str'>
7
<class 'str'>
19
<class 'int'>
창원
합포
<class 'str'>
8
<class 'str'>
19
<class 'int'>
부산
서구
<class 'str'>
9
<class 'str'>
19
<class 'int'>
부산
사하
<class 'str'>
10
<class 'str'>
19
<class 'int'>
부산
남구
<class 'str'>
11
<class 'str'>
19
<class 'int'>
함평
<class 'str'>
1
<class 'str'>
20
<class 'int'>
담양
<class 'str'>
2
<class 'str'>
20
<class 'int'>
순창
<class 'str'>
3
<class 'str'>
20
<class 'int'>
구례
<class 'str'>
4
<class 'str'>
20
<class 'int'>
하동
<class 'str'>
5
<class 'str'>
20
<class 'int'>
창원
의창
<class 'str'>
6
<class 'str'>
20
<class 'int'>
창원
성산
<class 'str'>
7
<class 'str'>
20
<class 'int'>
창원
진해
<class 'str'>
8
<class 'str'>
20
<class 'int'>
김해
<class 'str'>
9
<class 'str'>
20
<class 'int'>
부산
영도
<class 'str'>
10
<class 'str'>
20
<class 'int'>
부산
수영
<class 'str'>
11
<class 'str'>
20
<class 'int'>
신안
<class 'str'>
0
<class 'str'>
21
<class 'int'>
무안
<class 'str'>
1
<class 'str'>
21
<class 'int'>
광주
광산
<class 'str'>
2
<class 'str'>
21
<class 'int'>
곡성
<class 'str'>
3
<class 'str'>
21
<class 'int'>
화순
<class 'str'>
4
<class 'str'>
21
<class 'int'>
광양
<class 'str'>
5
<class 'str'>
21
<class 'int'>
사천
<class 'str'>
6
<class 'str'>
21
<class 'int'>
창원
회원
<class 'str'>
7
<class 'str'>
21
<class 'int'>
통영
<class 'str'>
8
<class 'str'>
21
<class 'int'>
목포
<class 'str'>
0
<class 'str'>
22
<class 'int'>
나주
<class 'str'>
1
<class 'str'>
22
<class 'int'>
광주
서구
<class 'str'>
2
<class 'str'>
22
<class 'int'>
광주
북구
<class 'str'>
3
<class 'str'>
22
<class 'int'>
순천
<class 'str'>
4
<class 'str'>
22
<class 'int'>
고흥
<class 'str'>
5
<class 'str'>
22
<class 'int'>
남해
<class 'str'>
6
<class 'str'>
22
<class 'int'>
고성
<class 'str'>
7
<class 'str'>
22
<class 'int'>
거제
<class 'str'>
8
<class 'str'>
22
<class 'int'>
해남
<class 'str'>
0
<class 'str'>
23
<class 'int'>
영암
<class 'str'>
1
<class 'str'>
23
<class 'int'>
광주
남구
<class 'str'>
2
<class 'str'>
23
<class 'int'>
광주
동구
<class 'str'>
3
<class 'str'>
23
<class 'int'>
여수
<class 'str'>
4
<class 'str'>
23
<class 'int'>
진도
<class 'str'>
0
<class 'str'>
24
<class 'int'>
강진
<class 'str'>
1
<class 'str'>
24
<class 'int'>
장흥
<class 'str'>
2
<class 'str'>
24
<class 'int'>
보성
<class 'str'>
3
<class 'str'>
24
<class 'int'>
완도
<class 'str'>
2
<class 'str'>
25
<class 'int'>
제주
<class 'str'>
5
<class 'str'>
25
<class 'int'>
서귀포
<class 'str'>
5
<class 'str'>
26
<class 'int'>

In [ ]:
     plt.annotate(dispname, (row['x']+0.5, row['y']+0.5), weight='bold',
                 fontsize=fontsize, ha='center', va='center', 
                 linespacing=linespacing)

 # 시도 경계 그린다.
for path in BORDER_LINES:
    ys, xs = zip(*path)
    plt.plot(xs, ys, c='black', lw=1.5)
 
plt.gca().invert_yaxis()
 #plt.gca().set_aspect(1)
 
plt.axis('off')
 
plt.tight_layout()
plt.show()